name: Send Daily Message

on:
  schedule:
    - cron: '0 23 * * *'    # 23:00 по UTC
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage'
          method: 'POST'
          data: '{"chat_id": "${{ secrets.CHAT_ID }}", "text": "Доброе утро! Как спалось?"}'
          contentType: 'application/json'
